name: ZAP Scan on Juice Shop

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    # Step 1: Run Juice Shop as a service
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
        options: >-
          --health-cmd="wget --spider -q http://localhost:3000"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      # Step 2: Wait for Juice Shop to be ready
      - name: Wait for Juice Shop to be healthy
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000; then
              echo "Juice Shop is up!"
              exit 0
            else
              echo "Waiting for Juice Shop..."
              sleep 5
            fi
          done
          echo "Juice Shop did not start in time"
          exit 1

      # Step 3: Run ZAP Baseline scan
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
          cmd_options: '-a'
