name: ZAP Scan on Juice Shop (Optie A + JUnit)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 5
          done
          echo "Juice Shop did not start in time"
          exit 1

      - name: Debug Juice Shop logs if failed
        if: failure()
        run: docker logs $(docker ps -q -f "ancestor=bkimminich/juice-shop")

      - name: Run ZAP Baseline Scan (HTML + JUnit XML)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
          cmd_options: '-a -r zap_report.html -x zap_report.xml'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.xml

      - name: Publish ZAP JUnit Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: zap_report.xml
